# Generated by Django 5.1.7 on 2025-03-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clubs', '0001_initial'),
        ('communities', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_clubs',
            field=models.ManyToManyField(blank=True, related_name='user_clubs', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_communities',
            field=models.ManyToManyField(blank=True, related_name='user_communities', to='communities.community'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='products.product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
