# Generated by Django 5.1.7 on 2025-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clubs', '0002_alter_club_image_alter_club_members'),
        ('communities', '0002_alter_community_image_alter_community_members'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_clubs',
            field=models.ManyToManyField(blank=True, related_name='user_clubs', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_communities',
            field=models.ManyToManyField(blank=True, related_name='user_communities', to='communities.community'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='products.product'),
        ),
    ]
