# Generated by Django 5.1.7 on 2025-03-22 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpeg', upload_to='clubs/')),
                ('members', models.ManyToManyField(blank=True, related_name='club_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
