# Generated by Django 4.2.7 on 2025-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['id'], name='clubs_club_id_78da8b_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['name'], name='clubs_club_name_657a0c_idx'),
        ),
    ]
