# Generated by Django 5.1.7 on 2025-03-22 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='clubs/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='club_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
